image: node:12

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv public publicfolder
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - general